services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - cloud-pixel-canvas-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=pixel_canvas
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    networks:
      - cloud-pixel-canvas-network

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pixel_canvas
    networks:
      - cloud-pixel-canvas-network

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - cloud-pixel-canvas-network

networks:
  cloud-pixel-canvas-network:
    driver: bridge
  
volumes:
  mongo_data:
